"""first version

Revision ID: 99787d96f30c
Revises: 
Create Date: 2019-11-04 21:38:06.901032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99787d96f30c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('tel', sa.String(length=20), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent')),
    sa.UniqueConstraint('name', name=op.f('uq_agent_name'))
    )
    op.create_table('deliverynote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nmuber', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('salesrecord_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliverynote')),
    sa.UniqueConstraint('nmuber', name=op.f('uq_deliverynote_nmuber'))
    )
    op.create_table('inoutreceipt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('in_out', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inoutreceipt')),
    sa.UniqueConstraint('number', name=op.f('uq_inoutreceipt_number'))
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=True),
    sa.Column('_quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product')),
    sa.UniqueConstraint('_quantity', name=op.f('uq_product__quantity')),
    sa.UniqueConstraint('model', name=op.f('uq_product_model')),
    sa.UniqueConstraint('name', name=op.f('uq_product_name')),
    sa.UniqueConstraint('number', name=op.f('uq_product_number'))
    )
    op.create_table('salesrecord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nmuber', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('applicant', sa.String(length=50), nullable=False),
    sa.Column('agent_name', sa.String(length=200), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('contact_address', sa.String(length=200), nullable=False),
    sa.Column('contact_tel', sa.String(length=20), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salesrecord')),
    sa.UniqueConstraint('nmuber', name=op.f('uq_salesrecord_nmuber'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('_password', sa.String(length=200), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('department', sa.Integer(), nullable=True),
    sa.Column('permission', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('name', name=op.f('uq_user_name'))
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('tel', sa.String(length=20), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name=op.f('fk_contact_agent_id_agent')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact'))
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.Column('deliverynote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deliverynote_id'], ['deliverynote.id'], name=op.f('fk_note_deliverynote_id_deliverynote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note'))
    )
    op.create_table('receipt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('inoutreceipt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inoutreceipt_id'], ['inoutreceipt.id'], name=op.f('fk_receipt_inoutreceipt_id_inoutreceipt')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_receipt_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipt')),
    sa.UniqueConstraint('quantity', name=op.f('uq_receipt_quantity'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipt')
    op.drop_table('note')
    op.drop_table('contact')
    op.drop_table('user')
    op.drop_table('salesrecord')
    op.drop_table('product')
    op.drop_table('inoutreceipt')
    op.drop_table('deliverynote')
    op.drop_table('agent')
    # ### end Alembic commands ###
