"""empty message

Revision ID: d60ab4817275
Revises: 
Create Date: 2019-08-02 21:40:13.776937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60ab4817275'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('name', name=op.f('uq_brands_name'))
    )
    op.create_table('catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['catalog.id'], name=op.f('fk_catalog_parent_id_catalog')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog')),
    sa.UniqueConstraint('name', name=op.f('uq_catalog_name'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('_password', sa.String(length=200), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('name', name=op.f('uq_user_name'))
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('package', sa.String(length=50), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('catalog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_materials_brand_id_brands')),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], name=op.f('fk_materials_catalog_id_catalog')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials')),
    sa.UniqueConstraint('number', name=op.f('uq_materials_number'))
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Text(), nullable=True),
    sa.Column('materials_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['materials_id'], ['materials.id'], name=op.f('fk_price_materials_id_materials')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price')
    op.drop_table('materials')
    op.drop_table('user')
    op.drop_table('catalog')
    op.drop_table('brands')
    # ### end Alembic commands ###
